// <auto-generated />
using System;
using GJApples.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GJApples.Migrations
{
    [DbContext(typeof(GJApplesDbContext))]
    [Migration("20240125205241_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GJApples.Models.AppleVariety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerPound")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppleVarieties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostPerPound = 1.20m,
                            ImageUrl = "url_to_honeycrisp_image",
                            IsActive = true,
                            Type = "Honeycrisp"
                        },
                        new
                        {
                            Id = 2,
                            CostPerPound = 0.95m,
                            ImageUrl = "url_to_granny_smith_image",
                            IsActive = true,
                            Type = "Granny Smith"
                        },
                        new
                        {
                            Id = 3,
                            CostPerPound = 1.10m,
                            ImageUrl = "url_to_fuji_image",
                            IsActive = true,
                            Type = "Fuji"
                        },
                        new
                        {
                            Id = 4,
                            CostPerPound = 0.85m,
                            ImageUrl = "url_to_gala_image",
                            IsActive = true,
                            Type = "Gala"
                        },
                        new
                        {
                            Id = 5,
                            CostPerPound = 1.15m,
                            ImageUrl = "url_to_pink_lady_image",
                            IsActive = true,
                            Type = "Pink Lady"
                        },
                        new
                        {
                            Id = 6,
                            CostPerPound = 0.90m,
                            ImageUrl = "url_to_braeburn_image",
                            IsActive = true,
                            Type = "Braeburn"
                        },
                        new
                        {
                            Id = 7,
                            CostPerPound = 0.80m,
                            ImageUrl = "url_to_red_delicious_image",
                            IsActive = true,
                            Type = "Red Delicious"
                        },
                        new
                        {
                            Id = 8,
                            CostPerPound = 0.85m,
                            ImageUrl = "url_to_golden_delicious_image",
                            IsActive = true,
                            Type = "Golden Delicious"
                        });
                });

            modelBuilder.Entity("GJApples.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Canceled")
                        .HasColumnType("boolean");

                    b.Property<int>("CustomerUserProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateOrdered")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("EmployeeUserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerUserProfileId");

                    b.HasIndex("EmployeeUserProfileId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Canceled = true,
                            CustomerUserProfileId = 6,
                            DateOrdered = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Canceled = true,
                            CustomerUserProfileId = 6,
                            DateOrdered = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Canceled = true,
                            CustomerUserProfileId = 7,
                            DateOrdered = new DateTime(2023, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Canceled = true,
                            CustomerUserProfileId = 6,
                            DateOrdered = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Canceled = true,
                            CustomerUserProfileId = 7,
                            DateOrdered = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Canceled = false,
                            CustomerUserProfileId = 7,
                            DateCompleted = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOrdered = new DateTime(2023, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeUserProfileId = 5
                        },
                        new
                        {
                            Id = 7,
                            Canceled = false,
                            CustomerUserProfileId = 7,
                            DateCompleted = new DateTime(2023, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOrdered = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeUserProfileId = 4
                        },
                        new
                        {
                            Id = 8,
                            Canceled = false,
                            CustomerUserProfileId = 7,
                            DateCompleted = new DateTime(2023, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOrdered = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeUserProfileId = 5
                        },
                        new
                        {
                            Id = 9,
                            Canceled = false,
                            CustomerUserProfileId = 6,
                            DateOrdered = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeUserProfileId = 4
                        },
                        new
                        {
                            Id = 10,
                            Canceled = false,
                            CustomerUserProfileId = 7,
                            DateOrdered = new DateTime(2023, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Canceled = false,
                            CustomerUserProfileId = 6,
                            DateOrdered = new DateTime(2023, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GJApples.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppleVarietyId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Pounds")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AppleVarietyId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppleVarietyId = 1,
                            OrderId = 1,
                            Pounds = 1.5m
                        },
                        new
                        {
                            Id = 2,
                            AppleVarietyId = 3,
                            OrderId = 1,
                            Pounds = 1.0m
                        },
                        new
                        {
                            Id = 3,
                            AppleVarietyId = 4,
                            OrderId = 1,
                            Pounds = 0.5m
                        },
                        new
                        {
                            Id = 4,
                            AppleVarietyId = 6,
                            OrderId = 1,
                            Pounds = 2.5m
                        },
                        new
                        {
                            Id = 5,
                            AppleVarietyId = 2,
                            OrderId = 2,
                            Pounds = 2.0m
                        },
                        new
                        {
                            Id = 6,
                            AppleVarietyId = 8,
                            OrderId = 2,
                            Pounds = 3.0m
                        },
                        new
                        {
                            Id = 7,
                            AppleVarietyId = 4,
                            OrderId = 2,
                            Pounds = 0.5m
                        },
                        new
                        {
                            Id = 8,
                            AppleVarietyId = 6,
                            OrderId = 2,
                            Pounds = 1.0m
                        },
                        new
                        {
                            Id = 9,
                            AppleVarietyId = 7,
                            OrderId = 3,
                            Pounds = 4.0m
                        },
                        new
                        {
                            Id = 10,
                            AppleVarietyId = 4,
                            OrderId = 3,
                            Pounds = 1.5m
                        },
                        new
                        {
                            Id = 11,
                            AppleVarietyId = 2,
                            OrderId = 3,
                            Pounds = 0.5m
                        },
                        new
                        {
                            Id = 12,
                            AppleVarietyId = 1,
                            OrderId = 3,
                            Pounds = 1.5m
                        },
                        new
                        {
                            Id = 13,
                            AppleVarietyId = 3,
                            OrderId = 4,
                            Pounds = 4.5m
                        },
                        new
                        {
                            Id = 14,
                            AppleVarietyId = 8,
                            OrderId = 4,
                            Pounds = 3.0m
                        },
                        new
                        {
                            Id = 15,
                            AppleVarietyId = 5,
                            OrderId = 4,
                            Pounds = 1.0m
                        },
                        new
                        {
                            Id = 16,
                            AppleVarietyId = 1,
                            OrderId = 4,
                            Pounds = 4.5m
                        },
                        new
                        {
                            Id = 17,
                            AppleVarietyId = 2,
                            OrderId = 4,
                            Pounds = 4.5m
                        },
                        new
                        {
                            Id = 18,
                            AppleVarietyId = 7,
                            OrderId = 4,
                            Pounds = 3.0m
                        },
                        new
                        {
                            Id = 19,
                            AppleVarietyId = 6,
                            OrderId = 5,
                            Pounds = 3.5m
                        },
                        new
                        {
                            Id = 20,
                            AppleVarietyId = 7,
                            OrderId = 5,
                            Pounds = 1.5m
                        },
                        new
                        {
                            Id = 21,
                            AppleVarietyId = 1,
                            OrderId = 5,
                            Pounds = 4.0m
                        },
                        new
                        {
                            Id = 22,
                            AppleVarietyId = 4,
                            OrderId = 5,
                            Pounds = 2.5m
                        },
                        new
                        {
                            Id = 23,
                            AppleVarietyId = 1,
                            OrderId = 6,
                            Pounds = 1.0m
                        },
                        new
                        {
                            Id = 24,
                            AppleVarietyId = 8,
                            OrderId = 6,
                            Pounds = 4.0m
                        },
                        new
                        {
                            Id = 25,
                            AppleVarietyId = 2,
                            OrderId = 6,
                            Pounds = 4.5m
                        },
                        new
                        {
                            Id = 26,
                            AppleVarietyId = 3,
                            OrderId = 7,
                            Pounds = 0.5m
                        },
                        new
                        {
                            Id = 27,
                            AppleVarietyId = 4,
                            OrderId = 7,
                            Pounds = 1.0m
                        },
                        new
                        {
                            Id = 28,
                            AppleVarietyId = 8,
                            OrderId = 8,
                            Pounds = 0.5m
                        },
                        new
                        {
                            Id = 29,
                            AppleVarietyId = 3,
                            OrderId = 8,
                            Pounds = 3.0m
                        },
                        new
                        {
                            Id = 30,
                            AppleVarietyId = 2,
                            OrderId = 8,
                            Pounds = 2.5m
                        },
                        new
                        {
                            Id = 31,
                            AppleVarietyId = 4,
                            OrderId = 8,
                            Pounds = 4.0m
                        },
                        new
                        {
                            Id = 32,
                            AppleVarietyId = 1,
                            OrderId = 8,
                            Pounds = 4.5m
                        },
                        new
                        {
                            Id = 33,
                            AppleVarietyId = 6,
                            OrderId = 8,
                            Pounds = 1.0m
                        },
                        new
                        {
                            Id = 34,
                            AppleVarietyId = 5,
                            OrderId = 8,
                            Pounds = 2.0m
                        },
                        new
                        {
                            Id = 35,
                            AppleVarietyId = 7,
                            OrderId = 8,
                            Pounds = 0.5m
                        },
                        new
                        {
                            Id = 36,
                            AppleVarietyId = 3,
                            OrderId = 9,
                            Pounds = 0.5m
                        },
                        new
                        {
                            Id = 37,
                            AppleVarietyId = 8,
                            OrderId = 9,
                            Pounds = 0.5m
                        },
                        new
                        {
                            Id = 38,
                            AppleVarietyId = 5,
                            OrderId = 9,
                            Pounds = 2.5m
                        },
                        new
                        {
                            Id = 39,
                            AppleVarietyId = 7,
                            OrderId = 9,
                            Pounds = 0.5m
                        },
                        new
                        {
                            Id = 40,
                            AppleVarietyId = 6,
                            OrderId = 9,
                            Pounds = 3.5m
                        },
                        new
                        {
                            Id = 41,
                            AppleVarietyId = 5,
                            OrderId = 10,
                            Pounds = 3.0m
                        },
                        new
                        {
                            Id = 42,
                            AppleVarietyId = 3,
                            OrderId = 10,
                            Pounds = 4.0m
                        },
                        new
                        {
                            Id = 43,
                            AppleVarietyId = 1,
                            OrderId = 10,
                            Pounds = 4.0m
                        },
                        new
                        {
                            Id = 44,
                            AppleVarietyId = 7,
                            OrderId = 10,
                            Pounds = 4.0m
                        },
                        new
                        {
                            Id = 45,
                            AppleVarietyId = 4,
                            OrderId = 10,
                            Pounds = 4.5m
                        },
                        new
                        {
                            Id = 46,
                            AppleVarietyId = 6,
                            OrderId = 10,
                            Pounds = 4.5m
                        },
                        new
                        {
                            Id = 47,
                            AppleVarietyId = 8,
                            OrderId = 10,
                            Pounds = 2.0m
                        },
                        new
                        {
                            Id = 48,
                            AppleVarietyId = 1,
                            OrderId = 11,
                            Pounds = 2.0m
                        },
                        new
                        {
                            Id = 49,
                            AppleVarietyId = 8,
                            OrderId = 11,
                            Pounds = 2.5m
                        },
                        new
                        {
                            Id = 50,
                            AppleVarietyId = 6,
                            OrderId = 11,
                            Pounds = 0.5m
                        });
                });

            modelBuilder.Entity("GJApples.Models.Tree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppleVarietyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DatePlanted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateRemoved")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppleVarietyId");

                    b.ToTable("Trees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppleVarietyId = 1,
                            DatePlanted = new DateTime(2015, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AppleVarietyId = 1,
                            DatePlanted = new DateTime(2016, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AppleVarietyId = 2,
                            DatePlanted = new DateTime(2017, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AppleVarietyId = 2,
                            DatePlanted = new DateTime(2018, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRemoved = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AppleVarietyId = 3,
                            DatePlanted = new DateTime(2019, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AppleVarietyId = 3,
                            DatePlanted = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AppleVarietyId = 4,
                            DatePlanted = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AppleVarietyId = 4,
                            DatePlanted = new DateTime(2022, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AppleVarietyId = 5,
                            DatePlanted = new DateTime(2016, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AppleVarietyId = 5,
                            DatePlanted = new DateTime(2017, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            AppleVarietyId = 6,
                            DatePlanted = new DateTime(2018, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AppleVarietyId = 6,
                            DatePlanted = new DateTime(2019, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AppleVarietyId = 7,
                            DatePlanted = new DateTime(2020, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AppleVarietyId = 7,
                            DatePlanted = new DateTime(2021, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AppleVarietyId = 8,
                            DatePlanted = new DateTime(2022, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AppleVarietyId = 8,
                            DatePlanted = new DateTime(2023, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AppleVarietyId = 1,
                            DatePlanted = new DateTime(2017, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            AppleVarietyId = 2,
                            DatePlanted = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRemoved = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            AppleVarietyId = 3,
                            DatePlanted = new DateTime(2019, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            AppleVarietyId = 4,
                            DatePlanted = new DateTime(2020, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GJApples.Models.TreeHarvestReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeUserProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("PoundsHarvested")
                        .HasColumnType("numeric");

                    b.Property<int>("TreeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeUserProfileId");

                    b.HasIndex("TreeId");

                    b.ToTable("TreeHarvestReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 45.5m,
                            TreeId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 23m,
                            TreeId = 1
                        },
                        new
                        {
                            Id = 3,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 32.25m,
                            TreeId = 2
                        },
                        new
                        {
                            Id = 4,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 50m,
                            TreeId = 2
                        },
                        new
                        {
                            Id = 5,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 58.75m,
                            TreeId = 3
                        },
                        new
                        {
                            Id = 6,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 54m,
                            TreeId = 3
                        },
                        new
                        {
                            Id = 7,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 57m,
                            TreeId = 4
                        },
                        new
                        {
                            Id = 8,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 28m,
                            TreeId = 5
                        },
                        new
                        {
                            Id = 9,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 38m,
                            TreeId = 5
                        },
                        new
                        {
                            Id = 10,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 28m,
                            TreeId = 6
                        },
                        new
                        {
                            Id = 11,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 45m,
                            TreeId = 6
                        },
                        new
                        {
                            Id = 12,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 30m,
                            TreeId = 7
                        },
                        new
                        {
                            Id = 13,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 49m,
                            TreeId = 7
                        },
                        new
                        {
                            Id = 14,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 52m,
                            TreeId = 8
                        },
                        new
                        {
                            Id = 15,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 38m,
                            TreeId = 8
                        },
                        new
                        {
                            Id = 16,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 56m,
                            TreeId = 9
                        },
                        new
                        {
                            Id = 17,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 27m,
                            TreeId = 9
                        },
                        new
                        {
                            Id = 18,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 50m,
                            TreeId = 10
                        },
                        new
                        {
                            Id = 19,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 16m,
                            TreeId = 10
                        },
                        new
                        {
                            Id = 20,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 15m,
                            TreeId = 11
                        },
                        new
                        {
                            Id = 21,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 35m,
                            TreeId = 11
                        },
                        new
                        {
                            Id = 22,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 26m,
                            TreeId = 12
                        },
                        new
                        {
                            Id = 23,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 56m,
                            TreeId = 12
                        },
                        new
                        {
                            Id = 24,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 31m,
                            TreeId = 13
                        },
                        new
                        {
                            Id = 25,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 50m,
                            TreeId = 13
                        },
                        new
                        {
                            Id = 26,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 40m,
                            TreeId = 14
                        },
                        new
                        {
                            Id = 27,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 38m,
                            TreeId = 14
                        },
                        new
                        {
                            Id = 28,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 46m,
                            TreeId = 15
                        },
                        new
                        {
                            Id = 29,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 24m,
                            TreeId = 15
                        },
                        new
                        {
                            Id = 30,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 41m,
                            TreeId = 16
                        },
                        new
                        {
                            Id = 31,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 46m,
                            TreeId = 16
                        },
                        new
                        {
                            Id = 32,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 42m,
                            TreeId = 17
                        },
                        new
                        {
                            Id = 33,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 52m,
                            TreeId = 17
                        },
                        new
                        {
                            Id = 34,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 55m,
                            TreeId = 18
                        },
                        new
                        {
                            Id = 35,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 51m,
                            TreeId = 19
                        },
                        new
                        {
                            Id = 36,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 19m,
                            TreeId = 19
                        },
                        new
                        {
                            Id = 37,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 26m,
                            TreeId = 20
                        },
                        new
                        {
                            Id = 38,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 50m,
                            TreeId = 20
                        },
                        new
                        {
                            Id = 39,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 16m,
                            TreeId = 1
                        },
                        new
                        {
                            Id = 40,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 43m,
                            TreeId = 1
                        },
                        new
                        {
                            Id = 41,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 26m,
                            TreeId = 2
                        },
                        new
                        {
                            Id = 42,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 18m,
                            TreeId = 2
                        },
                        new
                        {
                            Id = 43,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 50m,
                            TreeId = 3
                        },
                        new
                        {
                            Id = 44,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 56m,
                            TreeId = 3
                        },
                        new
                        {
                            Id = 45,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 58m,
                            TreeId = 4
                        },
                        new
                        {
                            Id = 46,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 31m,
                            TreeId = 5
                        },
                        new
                        {
                            Id = 47,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 28m,
                            TreeId = 6
                        },
                        new
                        {
                            Id = 48,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 51m,
                            TreeId = 7
                        },
                        new
                        {
                            Id = 49,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 41m,
                            TreeId = 8
                        },
                        new
                        {
                            Id = 50,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 27m,
                            TreeId = 9
                        },
                        new
                        {
                            Id = 51,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 25m,
                            TreeId = 10
                        },
                        new
                        {
                            Id = 52,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 16m,
                            TreeId = 11
                        },
                        new
                        {
                            Id = 53,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 41m,
                            TreeId = 12
                        },
                        new
                        {
                            Id = 54,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 19m,
                            TreeId = 13
                        },
                        new
                        {
                            Id = 55,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 42m,
                            TreeId = 14
                        },
                        new
                        {
                            Id = 56,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 37m,
                            TreeId = 15
                        },
                        new
                        {
                            Id = 57,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 20m,
                            TreeId = 16
                        },
                        new
                        {
                            Id = 58,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 26m,
                            TreeId = 17
                        },
                        new
                        {
                            Id = 59,
                            EmployeeUserProfileId = 2,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 23m,
                            TreeId = 18
                        },
                        new
                        {
                            Id = 60,
                            EmployeeUserProfileId = 3,
                            HarvestDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PoundsHarvested = 17m,
                            TreeId = 19
                        });
                });

            modelBuilder.Entity("GJApples.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "101 Main Street",
                            FirstName = "Admina",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            LastName = "Strator"
                        },
                        new
                        {
                            Id = 2,
                            Address = "102 Harvest Lane",
                            FirstName = "Josh",
                            IdentityUserId = "8c3605d2-c0da-4592-8879-0c71dc3c02c4",
                            LastName = "Harvester"
                        },
                        new
                        {
                            Id = 3,
                            Address = "103 Harvest Lane",
                            FirstName = "Haley",
                            IdentityUserId = "3a64b2c1-7780-40f1-a393-8edb30c4b2ab",
                            LastName = "Harvester"
                        },
                        new
                        {
                            Id = 4,
                            Address = "104 Picker Street",
                            FirstName = "Chris",
                            IdentityUserId = "83aab5f4-67ba-4da9-940e-fef0ce8597bd",
                            LastName = "Picker"
                        },
                        new
                        {
                            Id = 5,
                            Address = "105 Picker Street",
                            FirstName = "Kyle",
                            IdentityUserId = "03d8deac-3687-4274-82c1-e1d32392d2de",
                            LastName = "Picker"
                        },
                        new
                        {
                            Id = 6,
                            Address = "106 Customer Road",
                            FirstName = "Debbie",
                            IdentityUserId = "c8c02266-41e6-414d-a1fc-14bbefef86a0",
                            LastName = "Customer"
                        },
                        new
                        {
                            Id = 7,
                            Address = "107 Customer Road",
                            FirstName = "Aaron",
                            IdentityUserId = "bc3a3871-4800-4061-8182-b965c9c109bc",
                            LastName = "Customer"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35",
                            ConcurrencyStamp = "a6ac2063-2160-45f1-b4fa-6298dc27aa92",
                            Name = "Admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = "8b2b3a2d-62f6-4f2b-8b3d-45b6a1f3b5b4",
                            ConcurrencyStamp = "ae0408a4-4857-4783-8e24-fddee342db05",
                            Name = "Harvester",
                            NormalizedName = "harvester"
                        },
                        new
                        {
                            Id = "f65f1f30-d0b1-4f59-a3c8-eb1f2e6757d3",
                            ConcurrencyStamp = "0b0297f6-01c1-4383-aaad-67e796a3ce52",
                            Name = "OrderPicker",
                            NormalizedName = "orderpicker"
                        },
                        new
                        {
                            Id = "d4f146bf-70c8-4d02-98ec-0b5f4b9d213f",
                            ConcurrencyStamp = "847a4e93-c308-4514-a8ab-f86a1c920904",
                            Name = "Customer",
                            NormalizedName = "customer"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1c09122e-6273-4aad-900a-03ee8ea59164",
                            Email = "admin@gjapples.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEJLjb4wYgqlXB9CBdXKzFBl91Kr16MAKsQKgX8Dop/6RnuEbK10a6G5UrABSEVjEGQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "730a4bab-704d-4e94-937f-14f53bcfc85f",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        },
                        new
                        {
                            Id = "8c3605d2-c0da-4592-8879-0c71dc3c02c4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b6e3289e-1077-4eff-8fe3-8872fd0a5dcc",
                            Email = "josh@gjapples.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAENUuBO7EOQDxSE3ZC9olHZ463R0pd3sslc/RnNX7fWPuEi+/gdb9LdYvI0zJI1chRg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8981249a-e577-4664-98c9-680d7781f460",
                            TwoFactorEnabled = false,
                            UserName = "Josh"
                        },
                        new
                        {
                            Id = "3a64b2c1-7780-40f1-a393-8edb30c4b2ab",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c822e364-cdbb-436c-af88-84f8a33ad693",
                            Email = "haley@gjapples.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEM6tHGH//Ns9Mi75okpMpPltUN6rz5a6bNy1pNVm3NVBg5/Khh7RoNEnCG1aRGkQUg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4ce3eb08-27e2-4973-be35-1f76f01090c0",
                            TwoFactorEnabled = false,
                            UserName = "Haley"
                        },
                        new
                        {
                            Id = "83aab5f4-67ba-4da9-940e-fef0ce8597bd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a69a6b70-f6d5-452d-bcb3-6e700f2c7bb3",
                            Email = "chris@gjapples.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEK8/AwboXxw9lNVAduutvNbjLmOWEp2ri4p1mSDPLsOBxTm5d61eZuBOZWE4T3Apqw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ecbd0074-f07a-4b39-bff5-578564b0728e",
                            TwoFactorEnabled = false,
                            UserName = "Chris"
                        },
                        new
                        {
                            Id = "03d8deac-3687-4274-82c1-e1d32392d2de",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2454581b-ae53-493f-a26e-0c9cf9ccb6cc",
                            Email = "kyle@gjapples.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAENE/7XF3U3QVrGNiYYCHIOVZ+qVfBoEkhmEGrde5kW3addJc2AA0wH5Dp6bZ+oGo4w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1cac1c21-023f-4528-a382-a27c64a5f580",
                            TwoFactorEnabled = false,
                            UserName = "Kyle"
                        },
                        new
                        {
                            Id = "c8c02266-41e6-414d-a1fc-14bbefef86a0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e11c18cd-f4c6-46d0-89b1-4e6bbc19f7cc",
                            Email = "debbie@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEGHSLZF7ilrzz3dBfaNFuBEc+LXhfl19SsElzPA0MijPSpGxLkWoH1FbPZUTa6lD+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2fe7d1f9-f104-4136-8b92-1125924b02a8",
                            TwoFactorEnabled = false,
                            UserName = "Debbie"
                        },
                        new
                        {
                            Id = "bc3a3871-4800-4061-8182-b965c9c109bc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c2fcc772-f905-4c6d-bf15-8ca17d641639",
                            Email = "aaron@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEILn9OQKHsYLi+BDDCh37yAPABE5ALTDizrOd45c925iw21hUVyYH8uFAPZnvs8uHw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "851c89b0-6f34-4478-9b63-bb09522488aa",
                            TwoFactorEnabled = false,
                            UserName = "Aaron"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        },
                        new
                        {
                            UserId = "8c3605d2-c0da-4592-8879-0c71dc3c02c4",
                            RoleId = "8b2b3a2d-62f6-4f2b-8b3d-45b6a1f3b5b4"
                        },
                        new
                        {
                            UserId = "3a64b2c1-7780-40f1-a393-8edb30c4b2ab",
                            RoleId = "8b2b3a2d-62f6-4f2b-8b3d-45b6a1f3b5b4"
                        },
                        new
                        {
                            UserId = "83aab5f4-67ba-4da9-940e-fef0ce8597bd",
                            RoleId = "f65f1f30-d0b1-4f59-a3c8-eb1f2e6757d3"
                        },
                        new
                        {
                            UserId = "03d8deac-3687-4274-82c1-e1d32392d2de",
                            RoleId = "f65f1f30-d0b1-4f59-a3c8-eb1f2e6757d3"
                        },
                        new
                        {
                            UserId = "c8c02266-41e6-414d-a1fc-14bbefef86a0",
                            RoleId = "d4f146bf-70c8-4d02-98ec-0b5f4b9d213f"
                        },
                        new
                        {
                            UserId = "bc3a3871-4800-4061-8182-b965c9c109bc",
                            RoleId = "d4f146bf-70c8-4d02-98ec-0b5f4b9d213f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GJApples.Models.Order", b =>
                {
                    b.HasOne("GJApples.Models.UserProfile", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerUserProfileId");

                    b.HasOne("GJApples.Models.UserProfile", "Employee")
                        .WithMany("CompletedOrders")
                        .HasForeignKey("EmployeeUserProfileId");

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("GJApples.Models.OrderItem", b =>
                {
                    b.HasOne("GJApples.Models.AppleVariety", "AppleVariety")
                        .WithMany("OrderItems")
                        .HasForeignKey("AppleVarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GJApples.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppleVariety");
                });

            modelBuilder.Entity("GJApples.Models.Tree", b =>
                {
                    b.HasOne("GJApples.Models.AppleVariety", "AppleVariety")
                        .WithMany("Trees")
                        .HasForeignKey("AppleVarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppleVariety");
                });

            modelBuilder.Entity("GJApples.Models.TreeHarvestReport", b =>
                {
                    b.HasOne("GJApples.Models.UserProfile", "Employee")
                        .WithMany("TreeHarvestReports")
                        .HasForeignKey("EmployeeUserProfileId");

                    b.HasOne("GJApples.Models.Tree", "Tree")
                        .WithMany("TreeHarvestReports")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("GJApples.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GJApples.Models.AppleVariety", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Trees");
                });

            modelBuilder.Entity("GJApples.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("GJApples.Models.Tree", b =>
                {
                    b.Navigation("TreeHarvestReports");
                });

            modelBuilder.Entity("GJApples.Models.UserProfile", b =>
                {
                    b.Navigation("CompletedOrders");

                    b.Navigation("Orders");

                    b.Navigation("TreeHarvestReports");
                });
#pragma warning restore 612, 618
        }
    }
}
